default:
  openai_api_key: "<OPENAI_API_KEY>"
  openai_organization_id: "<OPENAI_ORGANIZATION_ID>"
  openai_organization_name: "<OPENAI_ORGANIZATION_NAME>"
  anthropic_api_key: "<ANTHROPIC_API_KEY>"
  gemini_api_key: "<GEMINI_API_KEY>"
  perplexity_api_key: "<PERPLEXITY_API_KEY>"
  tavily_api_key: "<TAVILY_API_KEY>"
  groq_api_key: "<GROQ_API_KEY>"
  openrouter_api_key: "<OPENROUTER_API_KEY>"
  serper_api_key: "<SERPER_API_KEY>"
  serpapi_api_key: "<SERPAPI_API_KEY>"
  huggingface_api_key: "<HUGGINGFACE_API_KEY>"
  langsmith_api_key: "<LANGSMITH_API_KEY>"
  transactional_api_key: "<TRANSACTIONAL_API_KEY>"
  vanna_api_key: "<VANNA_API_KEY>"

